# Permalinks
permalink:      /:categories/:title/ #/:year-:month-:day/:title
paginate: 5 # 페이지 나누기
paginate_path: /posts/page:num/
# Setup
title:          Jaekyu Kong
baseurl:        ""
url:            "janzzle.github.io"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  # - jekyll-sitemap
  # - jekyll-gist
  # - jekyll-feed
  # - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Jaekyu Kong
  url:          janzzle.github.io
  email:        janzzleworld@gmail.com  
  github:       janzzle
  twitter:      #

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/janzzle/janzzle.github.io

category_dir: category/
tag_dir: tag/

#
collections:
  authors:
  category:
    output: true

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true